### PR TITLE
[WP] More update on Git status

### PR DESCRIPTION
**Pull request by isbm**
My quick hacks to clone more/less Bobthefish on Git. If that is useful...
Probably I should delete "dirty" colors too though.

### CODE REVIEW

**Comment by simnalamburt** [comment]
Calling the same `command git status --porcelain` three time will make shellder three times slow. How about storing the result in a variable?

**Comment by isbm** [comment]
Absolutely agreed. Let me think. But the direction is OK? Essentially, I love Bobshefish a lot and missing it. But constantly majorly broken Fish itself and an absence of Emacs shortcuts makes it unusable for me.

I will try harder. :wink:

**Comment by simnalamburt** [comment]
Direction is totally fine :) Thank you

2020년 2월 21일 (금) 22:04, Bo Maryniuk <notifications@github.com>님이 작성:

**Review by simnalamburt — APPROVED** [review]

**Comment by simnalamburt** [comment]
I've merged it first :) Please feel free to optimize the `command git status --porcelain` part later!

**Comment by isbm** [comment]
Great, I will definitely optimise it, since I am using it myself :rofl:

**Pull request merged**
